const fs = require('node:fs');
const path = require('node:path');

const pkgPath = path.join(__dirname, '..', 'projects', 'sic-ng', 'package.json');
const outPath = path.join(__dirname, '..', 'projects', 'sic-ng', 'src', 'lib', 'version.ts');

const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));

const contents = `// Auto-generated by scripts/sync-version.js from projects/sic-ng/package.json — do not edit by hand.
export const SIC_NG_VERSION = '${pkg.version}';
`;

fs.writeFileSync(outPath, contents);

console.log(`sic-ng: synced version.ts to ${pkg.version}`);
